### PR TITLE
exercises

### PR DESCRIPTION
**Pull request by Tsolmon17**
### Summary
question 4 answer is provided now

### Bug Fixes/New Features
 - added a function that was undefined before
 - question 4 answer

### How to Verify
n/a
### Side Effects
n/a
### Resolves
n/a
### Tests
n/a

### Code Reviewer(s)
@amirziai

### CODE REVIEW

**Comment by amirziai** [comment]
@Tsolmon17 p-value for part 4 is `0.862`, can you still reject `H0`?

**Comment by Tsolmon17** [comment]
with p-value of 0.862 H0 is not rejected. Sorry when I was running it earlier, I was getting a p-value of 0. I resubmitted with correct answer. I'm assuming the changes are automatically reflected in the PR.

**Review by amirziai — APPROVED** [review]
Looks good. Thanks for making the changes. Hope everything makes sense now.

Ideally you want each exercise/change to happen on its own branch but we're good for now. Feel free to merge this in.

**Comment by Tsolmon17** [comment]
I just noticed that the clustering exercise I'm working on got pushed here as well. I followed the steps and created a new branch and everything. Not sure what happened here.

**Pull request merged**
